spring:
  application:
    name: eureka-server1

server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
