spring:
  application:
    name: gateway
server:
  port: 7003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

zuul:
  routes:
    admin-cloud-client:
      path: /admin-cloud-client/v1.0/**
      servicesId: admin-cloud-client

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 500
  SocketTimeut: 500
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
